"use client";

import { useMemo, useRef, useState } from "react";
import Link from "next/link";
import {
  Copy,
  Download,
  FileCode2,
  FileText,
  Image as ImageIcon,
  Play,
  Trash2,
  Upload,
} from "lucide-react";
import type { AttachmentDto } from "@angy/shared";
import { cx } from "../../lib/cx";
import { formatBytes, timeAgo } from "../../lib/time";
import { Button } from "../ui/Button";
import { Callout } from "../ui/Callout";
import { Progress } from "../ui/Feedback";
import { Chip } from "../ui/Tag";
import { useToast } from "../ui/ToastProvider";
import styles from "./attachments.module.css";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001";
const QUOTA_BYTES = 50 * 1024 * 1024 * 1024;

type Filter = "all" | "images" | "documents" | "video";

function kind(a: AttachmentDto): Filter {
  if (a.mimeType.startsWith("image/")) return "images";
  if (a.mimeType.startsWith("video/")) return "video";
  return "documents";
}

function TypeIcon({ a }: { a: AttachmentDto }) {
  const k = kind(a);
  if (k === "video") return <Play size={26} style={{ color: "var(--lilac)" }} />;
  if (k === "images") return <ImageIcon size={26} style={{ color: "var(--accent)" }} />;
  if (a.mimeType.includes("json") || a.mimeType.includes("javascript"))
    return <FileCode2 size={26} style={{ color: "var(--sage)" }} />;
  return <FileText size={26} style={{ color: "var(--clay)" }} />;
}

const PREVIEW_BG: Record<Filter, string> = {
  all: "var(--surface)",
  images: "var(--accent-soft)",
  documents: "var(--clay-soft)",
  video: "var(--lilac-soft)",
};

export function AttachmentsView({
  initial,
  pages,
  spaceKey,
}: {
  initial: AttachmentDto[];
  pages: { id: string; title: string }[];
  spaceKey: string;
}) {
  const [items, setItems] = useState(initial);
  const [filter, setFilter] = useState<Filter>("all");
  const [selectedId, setSelectedId] = useState<string | null>(initial[0]?.id ?? null);
  const [targetPage, setTargetPage] = useState(pages[0]?.id ?? "");
  const [busy, setBusy] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const visible = useMemo(
    () => (filter === "all" ? items : items.filter((a) => kind(a) === filter)),
    [items, filter],
  );
  const selected = items.find((a) => a.id === selectedId) ?? null;
  const totalBytes = items.reduce((sum, a) => sum + a.sizeBytes, 0);

  async function upload(file: File) {
    if (!targetPage) return;
    setBusy(true);
    try {
      const form = new FormData();
      form.append("file", file);
      const res = await fetch(`${API_URL}/pages/${targetPage}/attachments`, {
        method: "POST",
        credentials: "include",
        body: form,
      });
      const body = await res.json();
      if (body.success) {
        setItems((prev) => [body.data as AttachmentDto, ...prev]);
        setSelectedId((body.data as AttachmentDto).id);
        toast("success", "File uploaded", (body.data as AttachmentDto).fileName);
      } else {
        toast("error", "Upload failed", body.error.message);
      }
    } finally {
      setBusy(false);
    }
  }

  async function remove(attachment: AttachmentDto) {
    setBusy(true);
    try {
      const res = await fetch(`${API_URL}/attachments/${attachment.id}`, {
        method: "DELETE",
        credentials: "include",
      });
      const body = await res.json();
      if (body.success) {
        setItems((prev) => prev.filter((a) => a.id !== attachment.id));
        setSelectedId(null);
        toast("success", "Moved to trash", `${attachment.fileName} is swept with the 30-day GC.`);
      } else {
        toast("error", "Delete failed", body.error.message);
      }
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className={styles.layout}>
      <div>
        <h1 className="t-title" style={{ fontSize: 32 }}>
          Attachments
        </h1>
        <p className={styles.subtitle}>
          Stored in S3 and served by content hash · thumbnails generated by the worker
        </p>

        <div className={styles.toolbar}>
          {(
            [
              ["all", "All files"],
              ["images", "Images"],
              ["documents", "Documents"],
              ["video", "Video"],
            ] as const
          ).map(([keyName, label]) => (
            <Chip key={keyName} selected={filter === keyName} onClick={() => setFilter(keyName)}>
              {label}
            </Chip>
          ))}
          <span className={styles.meter}>
            {formatBytes(totalBytes)} of {formatBytes(QUOTA_BYTES)}
            <Progress value={Math.min(100, (totalBytes / QUOTA_BYTES) * 100)} hue="sage" />
          </span>
          <select
            value={targetPage}
            onChange={(e) => setTargetPage(e.target.value)}
            style={{ maxWidth: 160 }}
            aria-label="Upload to page"
          >
            {pages.map((p) => (
              <option key={p.id} value={p.id}>
                {p.title}
              </option>
            ))}
          </select>
          <Button
            icon={<Upload size={14} />}
            disabled={busy || !targetPage}
            onClick={() => fileInput.current?.click()}
          >
            Upload
          </Button>
          <input
            ref={fileInput}
            type="file"
            hidden
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) void upload(file);
              e.target.value = "";
            }}
          />
        </div>

        <div className={styles.grid}>
          {visible.map((a) => (
            <button
              key={a.id}
              className={cx(styles.card, a.id === selectedId && styles.cardSelected)}
              onClick={() => setSelectedId(a.id)}
            >
              <div className={styles.preview} style={{ background: PREVIEW_BG[kind(a)] }}>
                {a.thumbnailUrl ? (
                  <img src={a.thumbnailUrl} alt={a.fileName} />
                ) : (
                  <TypeIcon a={a} />
                )}
              </div>
              <div className={styles.cardBody}>
                <div className={styles.cardName}>{a.fileName}</div>
                <div className={styles.cardMeta}>
                  {a.width && a.height ? `${a.width} × ${a.height} · ` : ""}
                  {formatBytes(a.sizeBytes)}
                </div>
              </div>
            </button>
          ))}
          {visible.length === 0 && (
            <p style={{ color: "var(--text-3)", fontSize: 13.5 }}>No files yet — upload one.</p>
          )}
        </div>
      </div>

      <aside className={styles.rail}>
        {selected && (
          <>
            <div className="t-caption">File details</div>
            <div className={styles.detailPreview} style={{ background: PREVIEW_BG[kind(selected)] }}>
              {selected.thumbnailUrl ? (
                <img src={selected.thumbnailUrl} alt={selected.fileName} />
              ) : (
                <div style={{ padding: 40 }}>
                  <TypeIcon a={selected} />
                </div>
              )}
            </div>
            <div className={styles.detailName}>{selected.fileName}</div>
            <div className={styles.detailRow}>
              <span className={styles.detailLabel}>Type</span>
              <span>{selected.mimeType}</span>
            </div>
            {selected.width && selected.height && (
              <div className={styles.detailRow}>
                <span className={styles.detailLabel}>Dimensions</span>
                <span>
                  {selected.width} × {selected.height}
                </span>
              </div>
            )}
            <div className={styles.detailRow}>
              <span className={styles.detailLabel}>Size</span>
              <span>{formatBytes(selected.sizeBytes)}</span>
            </div>
            <div className={styles.detailRow}>
              <span className={styles.detailLabel}>Uploaded</span>
              <span>
                {selected.uploadedByName} · {timeAgo(selected.createdAt)}
              </span>
            </div>
            {selected.usedOnPages.length > 0 && (
              <div className={styles.detailRow}>
                <span className={styles.detailLabel}>Used on</span>
                <span className={styles.detailUsage}>
                  {selected.usedOnPages.length === 1
                    ? selected.usedOnPages[0]!.title
                    : `${selected.usedOnPages.length} pages`}
                  {selected.usedOnPages.length > 1 &&
                    selected.usedOnPages.map((p) => (
                      <Link key={p.id} href={`/s/${spaceKey}/${p.id}`} className={styles.usageLink}>
                        {p.title}
                      </Link>
                    ))}
                </span>
              </div>
            )}
            <div className="t-caption">Content hash</div>
            <div className={styles.hashBox} title={selected.sha256}>
              sha256:{selected.sha256.slice(0, 12)}…{selected.sha256.slice(-4)}
              <Copy size={12} style={{ marginLeft: 6, verticalAlign: -2 }} />
            </div>
            {selected.signed && (
              <Callout tone="hardRule">
                This space is private, so the file is served through a short-lived signed URL.
              </Callout>
            )}
            <div className={styles.actions}>
              <Button
                href={selected.url}
                target="_blank"
                rel="noreferrer"
                variant="secondary"
                icon={<Download size={14} />}
                style={{ flex: 1 }}
              >
                Download
              </Button>
              <Button
                variant="danger"
                icon={<Trash2 size={14} />}
                disabled={busy}
                onClick={() => void remove(selected)}
              >
                Delete
              </Button>
            </div>
          </>
        )}
      </aside>
    </div>
  );
}
